### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by magnusviri** [marcio199226/ytd#3]
I just downloaded v0.4.1-alpha and tried to launch it and it wont launch with the message: `“ytd” is damaged and can’t be opened. You should move it to the Trash.` I had to manually remove the quarantine extended attribute to get it to work (`xattr -cr /Users/jeng/Downloads/ytd.app`).

**Comment by marcio199226** [comment]
Hi since my app is not signed with any dev certificate and is distributed by github I think is normal that you have to manage some permissions and "allow" this app to be runned otherwise macos will warn you about apps not distrubuted "officialy". I may wrong because I'm not a daily mac user but if I'm not wrong I had to enable "allow apps from anywhere" and put my bundled app out of quarantine.
